services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_broker
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - app-network

  app-base:
    image: app-base
    build:
      context: .
      dockerfile: ./app/Dockerfile
    env_file:
      - ./app/.env.docker
    environment:
      - APP_ENV=PROD
    volumes:
      - ./app/data:/app/data
    networks:
      - app-network

  worker:
    container_name: celery_worker
    image: app-base
    working_dir: /app
    env_file:
      - ./app/.env.docker
    environment:
      - APP_ENV=PROD
      - PYTHONPATH=/app
    command: celery -A app.services.worker worker --loglevel=info  --concurrency=1 --prefetch-multiplier=1
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./app/data:/app/data
    networks:
      - app-network

  back_end:
    container_name: server
    image: app-base
    env_file:
      - ./app/.env.docker
    environment:
      - APP_ENV=PROD
      - PYTHONPATH=/app
    volumes:
      - ./app/data:/app/data
    ports:
      - 8000:8000
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  front_end:
    container_name: client
    build:
      context: ./front_end
    ports:
      - 3000:3000
    depends_on:
      - back_end
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
